[project]
name = "visulogic-backend"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
    "fastapi==0.116.1",
    "pydantic-settings==2.10.1",
    "python-multipart==0.0.20",
    "pillow==11.3.0",
    "opencv-python-headless==4.6.0.66",
    "numpy==2.0.2",
    "networkx==3.4.2",
    "sqlalchemy==2.0.38",
]

